version: "3.9"

services:
  ros2_main:
    build:
      context: ./ros2_main
    container_name: ros2_main
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # depends_on:
    #   - redis
    #   - kuka
    #   - scanner
    networks:
      - ros-network
  pygui:
    build:
      context: ./py_gui
    container_name: pygui
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    depends_on:
      - ros2_main
    stdin_open: true
    tty: true
    networks:
      - ros-network

  # gui:
  #   build:
  #     context: ./gui
  #   container_name: gui
  #   ports:
  #     - "3000:3000"  # frontend port exposed to your host
  #   depends_on:
  #     - ros2_main
  #   stdin_open: true
  #   tty: true
  # redis:
  #   image: redis:7
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  # data_analysis:
  #   image: python
  # kuka:
  #   build:
  #     context: kuka_arm
  #     dockerfile: Dockerfile
  #   container_name: kuka_ros2_container
  #   network_mode: host
  # camera:

  scanner:
    build: ./scanner
  

networks:
  ros-network:
    driver: bridge  
  
  
