box_filter_pcl_manager:
  ros__parameters:
    input_frame: camera_color_optical_frame

cropbox:
  ros__parameters:
    input_frame: camera_color_optical_frame
    min_x: -0.01
    max_x: 0.01
    min_y: -0.01
    max_y: 0.01
    min_z: 0.0
    max_z: 0.5

voxel_grid:
  ros__parameters:
    input_frame: camera_color_optical_frame
    leaf_size: 0.005